### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by Demonwd** [GDoom/DragonBonesJava#1]
Hello! Good job! How to work with skeleton.json version 4.0 or 4.5?

**Comment by 120318** [comment]
I will finish 4.0 version skileton.json and 1.0+ version libgdx soon.

**Comment by Demonwd** [comment]
Thanks for your answer, and for your work. Best regards.
--
Отправлено из Mail.Ru для Android воскресенье, 21 августа 2016г., 08:03 +0600 от GDoom  notifications@github.com :
